### PR TITLE
Allow customization and extension of lockfile metadata headers

### PR DESCRIPTION
**Pull request by maresb**
Here is an explanation of this PR through examples, showing only the resulting headers.

I have not yet written any tests or updated the README. Do these features look good?

```bash
conda-lock -f environment.yml --metadata=previous
# Generated by conda-lock.
# platform: win-64
# input_hash: f15a045753a401da73dd7c1693fd031e0ad41c0b4c9ca8545c0a8ab56c21d16c
@EXPLICIT

conda-lock -f environment.yml
# ---
# conda-lock-metadata:
#   about: This lockfile was generated by conda-lock to ensure reproducibility.
#   platform: win-64
#   input_hash: f15a045753a401da73dd7c1693fd031e0ad41c0b4c9ca8545c0a8ab56c21d16c
# ...
@EXPLICIT

conda-lock -f environment.yml "--comment=$(cat README.txt)"
# ---
# conda-lock-metadata:
#   about: This lockfile was generated by conda-lock to ensure reproducibility.
#   platform: win-64
#   input_hash: f15a045753a401da73dd7c1693fd031e0ad41c0b4c9ca8545c0a8ab56c21d16c
#   comment: |-
#     Contents of README.txt
#     ¡the second line! 😃
# ...
@EXPLICIT

conda-lock -f environment.yml --metadata=all
# ---
# conda-lock-metadata:
#   about: This lockfile was generated by conda-lock to ensure reproducibility.
#   command: conda-lock -f environment.yml --metadata=all
#   command_with_path: /root/conda/envs/conda-lock/bin/conda-lock -f environment.yml --metadata=all
#   comment: null
#   conda_lock_version: 0.11.3.dev0+gf2ba8d4.d20210904
#   created_by: root
#   input_hash: f15a045753a401da73dd7c1693fd031e0ad41c0b4c9ca8545c0a8ab56c21d16c
#   platform: win-64
#   timestamp: 2021-09-05 23:43:18+02:00
# ...
@EXPLICIT

conda-lock -f environment.yml --metadata=created_by,comment,command,timestamp --comment="Run the following command to update this project's dependencies."
# ---
# conda-lock-metadata:
#   created_by: mares
#   comment: |-
#     Run the following command to update this project's dependencies.
#   command: conda-lock -f environment.yml --metadata=created_by,comment,command,timestamp '--comment=Run the following command to update this project'"'"'s dependencies:'
#   timestamp: 2021-09-05 23:51:07+02:00
# ...
@EXPLICIT
```

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
This would almost certainly have to be an opt-in not an opt-out feature

**Comment by maresb** [comment]
@mariusvniekerk, easy enough if I set the default to "previous". Any other feedback?

**Comment by mariusvniekerk** [comment]
We might want to explicity version the metadata header version (with no version being the simple legacy form)

**Comment by maresb** [comment]
I implemented your suggestions.

I realize now that I may have misinterpreted your suggestion for versioning metadata...

Do you mean like there would be a flag `--metadata-version=n` and in the future we support all previous versions of metadata? If so, that seems like a good idea. Maybe it would make sense to have `--metadata-version` default to `latest` so that pinning is opt-in, but in the absence of `--metadata` it defaults to v0.

What sort of versioning would make sense? I'm thinking semver major-only so that we'd only increment when there's a breaking change.

The new behavior of my two respective commits:

```bash
conda-lock -f environment.yml
# Generated by conda-lock.
# platform: win-64
# input_hash: f15a045753a401da73dd7c1693fd031e0ad41c0b4c9ca8545c0a8ab56c21d16c
@EXPLICIT

conda-lock -f environment.yml --metadata=all
# ---
# conda-lock-metadata:
#   about: This lockfile was generated by conda-lock to ensure reproducibility.
#   command: conda-lock -f environment.yml --metadata=all
#   command_with_path: /root/conda/envs/conda-lock/bin/conda-lock -f environment.yml --metadata=all
#   comment: null
#   conda_lock_version: 0.11.3.dev0+gf2ba8d4.d20210904
#   created_by: root
#   input_hash: f15a045753a401da73dd7c1693fd031e0ad41c0b4c9ca8545c0a8ab56c21d16c
#   metadata_version: 1
#   platform: win-64
#   timestamp: 2021-09-08 20:12:23+02:00
# ...
@EXPLICIT
```

**Comment by mariusvniekerk** [comment]
Yeah that looks good to me as an output

**Comment by maresb** [comment]
By my logic, I think `comment` should be included even when null. My reason is that `all` is an alias for all fields, and that way you can use it to view all the available fields as a sort of documentation. Afterwards, if you care about privacy and data leakage, you should select just the ones you want to keep. But if you're not convinced I'll change it.

Regarding the hash filtering in the tests, the output should now be identical unless I made a mistake.

Unfortunately I won't have any time until next week to work on this.

**Comment by wolfv** [comment]
@maresb maybe you're interested in chiminig in here: https://github.com/mamba-org/mamba/issues/1209

**Comment by maresb** [comment]
Cool, thanks! Unfortunately it will be a while before I can get to this.

**Comment by maresb** [comment]
This is stale.

**Pull request closed without merging**
