### PR TITLE
Bump CI from 3.8 -> 3.10

### PR DESCRIPTION
**Pull request by ericdill**

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
The errors here do seem like a real set of errors

**Comment by ericdill** [comment]
all of these tests pass locally with python 3.10. how do I trigger CI again?

**Comment by ericdill** [comment]
do you want to set a minimum python version on this? maybe 3.7 -> 3.8?

**Comment by mariusvniekerk** [comment]
Pretty sure we have this in now already, closing

**Pull request closed without merging**
