### PR TITLE
Add support for poetry dependency groups

### PR DESCRIPTION
**Pull request by mariusvniekerk**
# Expand poetry support

Add support for https://python-poetry.org/docs/master/managing-dependencies/#dependency-groups 

## Checklist

- [x] Added a test against the poetry file from ibis (https://github.com/ibis-project/ibis/blob/3.2.0/pyproject.toml)
- [ ] Update documentation

### CODE REVIEW

**Comment by maresb** [comment]
I dislike this approach, especially since it unnecessarily binds us to Poetry, which in my experience has not been particularly friendly to the Conda community. 

To elaborate on https://github.com/conda-incubator/conda-lock/issues/311#issuecomment-1379723255, I'd rather take a build-system-agnostic approach via [PEP 517](https://peps.python.org/pep-0517/). Most build-backends define the [prepare_metadata_for_build_wheel](https://peps.python.org/pep-0517/#prepare-metadata-for-build-wheel) function. For example, from `main` in `conda-lock` in an environment with the build requirements installed, I can run

```python
from pathlib import Path
import hatchling.build as b

md_dir = Path("/tmp/md")
md_dir.mkdir(exist_ok=True)
md_subdir = b.prepare_metadata_for_build_wheel(metadata_directory=md_dir)
requirements = [line.split(": ", maxsplit=1)[1] for line in md.splitlines() if line.startswith("Requires-Dist: ")]
extras = [line.split(": ", maxsplit=1)[1] for line in md.splitlines() if line.startswith("Provides-Extra: ")]
```

which produces
```python
requirements = ['cachecontrol[filecache]>=0.12.9',
 'cachy>=0.3.0',
 'click-default-group',
 'click>=8.0',
 'clikit>=0.6.2',
 'crashtest>=0.3.0',
 'ensureconda>=1.3',
 'html5lib>=1.0',
 "importlib-metadata>=1.7.0; python_version <= '3.7'",
 'jinja2',
 'keyring>=21.2.0',
 'packaging>=20.4',
 'pkginfo>=1.4',
 'pydantic>=1.8.1',
 'pyyaml>=5.1',
 'requests>=2.18',
 'ruamel-yaml',
 "tomli; python_version < '3.11'",
 'tomlkit>=0.7.0',
 'toolz<1.0.0,>=0.12.0',
 'typing-extensions',
 'virtualenv>=20.0.26',
 "poetry==1.1.*; extra == 'pip-support'"]
extras = ['pip-support']
```

**Comment by mariusvniekerk** [comment]
This https://pypa-build.readthedocs.io/en/latest/api.html#module-build.util looks like the best potential solution?

**Comment by mariusvniekerk** [comment]
Actually the dependency groups do not make it into the wheel metadata.  They are more akin to hatch https://hatch.pypa.io/latest/config/environment/overview/ as well.  Probably worth adding support for that too.

**Comment by maresb** [comment]
I'm confused... aren't dependency groups in the metadata as `Provides-Extra`?

**Comment by maresb** [comment]
I just checked your ibis example, and there the metadata looks like
```python
('Provides-Extra', 'all')
('Provides-Extra', 'bigquery')
('Provides-Extra', 'clickhouse')
('Provides-Extra', 'dask')
('Provides-Extra', 'datafusion')
('Provides-Extra', 'decompiler')
('Provides-Extra', 'duckdb')
('Provides-Extra', 'geospatial')
('Provides-Extra', 'impala')
('Provides-Extra', 'mssql')
('Provides-Extra', 'mysql')
('Provides-Extra', 'pandas')
('Provides-Extra', 'polars')
('Provides-Extra', 'postgres')
('Provides-Extra', 'pyspark')
('Provides-Extra', 'snowflake')
('Provides-Extra', 'sqlite')
('Provides-Extra', 'trino')
('Provides-Extra', 'visualization')
('Requires-Dist', 'GeoAlchemy2 (>=0.6.3,<1) ; extra == "all" or extra == "geospatial"')
('Requires-Dist', 'atpublic (>=2.3,<4)')
('Requires-Dist', 'black (>=22.1.0,<23) ; extra == "all" or extra == "decompiler"')
...
```

so `dev`, `test`, and `docs` are missing. :disappointed:

**Review by maresb — APPROVED** [review]

**Comment by mariusvniekerk** [comment]
Yeah so i think we still want this kind of stuff as it is pretty commonly used.  Hatch also has a thing called https://hatch.pypa.io/latest/environment/ that rather closely matches this.  Their one is even harder to parse annoyingly enough

**Pull request merged**
