### PR TITLE
Ci fixup

### PR DESCRIPTION
**Pull request by wolfv**

### CODE REVIEW

**Comment by wolfv** [comment]
so running with `-vvv` gives a bit more information... 

```
* Hostname 'conda.anaconda.org' was found in DNS cache
*   Trying 104.17.92.24:443...
* Connected to conda.anaconda.org (104.17.92.24) port 443 (#0)
* ALPN, offering http/1.1
* error setting certificate verify locations:
  CAfile: /home/conda/feedstock_root/build_artifacts/micromamba_1605202753479/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh
* Closing connection 0
* Connected to conda.anaconda.org (104.17.92.24) port 443 (#1)
* ALPN, offering http/1.1
* error setting certificate verify locations:
  CAfile: /home/conda/feedstock_root/build_artifacts/micromamba_1605202753479/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh
```

So it seems that curl has a hard-coded search path for the CA root certificates in the build prefix (which would normally be replaced by conda / mamba when installing) to find the certificates in the `ca-certificates` package.
However, I am convinced that micromamba works on github actions since I am using it myself. So normally I woudl expect it to look in other places as well. There is also the `REQUESTS_CA_BUNDLE` environment variable that can be used to point to the root CA bundle.

Do you have any idea why this doesn't work inside pytest but works on github actions otherwise? For example, this ran fine today: https://github.com/mamba-org/boa/pull/92/checks?check_run_id=1416817607

**Comment by wolfv** [comment]
I can run another test suite with -vvv somewhere else on github actions and see what it gives.

**Comment by marcelotrevisani** [comment]
> so running with `-vvv` gives a bit more information...
> 
> ```
> * Hostname 'conda.anaconda.org' was found in DNS cache
> *   Trying 104.17.92.24:443...
> * Connected to conda.anaconda.org (104.17.92.24) port 443 (#0)
> * ALPN, offering http/1.1
> * error setting certificate verify locations:
>   CAfile: /home/conda/feedstock_root/build_artifacts/micromamba_1605202753479/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh
> * Closing connection 0
> * Connected to conda.anaconda.org (104.17.92.24) port 443 (#1)
> * ALPN, offering http/1.1
> * error setting certificate verify locations:
>   CAfile: /home/conda/feedstock_root/build_artifacts/micromamba_1605202753479/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh
> ```
> 
> So it seems that curl has a hard-coded search path for the CA root certificates in the build prefix (which would normally be replaced by conda / mamba when installing) to find the certificates in the `ca-certificates` package.
> However, I am convinced that micromamba works on github actions since I am using it myself. So normally I woudl expect it to look in other places as well. There is also the `REQUESTS_CA_BUNDLE` environment variable that can be used to point to the root CA bundle.
> 
> Do you have any idea why this doesn't work inside pytest but works on github actions otherwise? For example, this ran fine today: https://github.com/mamba-org/boa/pull/92/checks?check_run_id=1416817607

uunn, I believe you should mark that test as serial test and run this mark without pytest-xdist, in that case just specifying ``-n0``

**Comment by wolfv** [comment]
Hmm, actually I had this issue before, and I fixed it with this:

    std::array<std::string, 6> cert_locations{
        "/etc/ssl/certs/ca-certificates.crt",                 // Debian/Ubuntu/Gentoo etc.
        "/etc/pki/tls/certs/ca-bundle.crt",                   // Fedora/RHEL 6
        "/etc/ssl/ca-bundle.pem",                             // OpenSUSE
        "/etc/pki/tls/cacert.pem",                            // OpenELEC
        "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem",  // CentOS/RHEL 7
        "/etc/ssl/cert.pem",                                  // Alpine Linux
    };


etc. etc. 

So now I am realizing that we're probably not calling the `set_network_options` function when dealing with explicit specs. Once we do that, this should work fine. Sorry!

**Comment by wolfv** [comment]
I have the fix: https://github.com/mamba-org/mamba/pull/595

Will try to release today!

**Comment by wolfv** [comment]
hey @marcelotrevisani there is one remaining issue in the current release of micromamba which I fixed yesterday: https://github.com/mamba-org/mamba/pull/609

with that conda-lock & micromamba should work pretty much fine :)

**Pull request closed without merging**
