### PR TITLE
Vendor Poetry

### LINKED ISSUE #235: Straighten out Poetry dependency chaos
I wonder if we need to depend on Poetry as a required dependency, since it shouldn't be necessary unless there's a `pip: [...]` section, right?

Poetry finally released a "stable" v1.2 a few days ago, but unfortunately not all is well. There are two blockers which currently make a conda-forge release impossible: 1. it contains a circular dependency with `poetry-plugin-export` which makes conda balk, and 2. there is no stable release of its dependency cleo v1.0.

In terms of testing, it's possible to install Poetry v1.2 / Cleo from conda-forge via dev labels.

In the meantime I've gotten fed up with Poetry, and discovered Hatch, which I like much better. (But it seems we are only using Poetry for its PyPI dependency solver, which Hatch doesn't have.) Currently I can't simultaneously install Poetry 1.1 and Hatch since they have [incompatible pins](https://github.com/pypa/hatch/issues/449) for the `packaging` dependency, and this means that I cannot simultaneously use recent versions of conda-lock with Hatch. :disappointed: 

So I have two questions:

1. Can we turn Poetry into an optional dependency?
2. How much must be changed here in conda-lock in order to accommodate Poetry v1.2?

### PR DESCRIPTION
**Pull request by maresb**
Closes #235

Still in early stages, but want to test with CI.

I haven't forgotten the [alternative proposal](https://github.com/conda-incubator/conda-lock/issues/235#issuecomment-1241985227) to write my own solver, but vendoring seems like the most straightforward place to start.

### CODE REVIEW

**Comment by maresb** [comment]
Current goals:

* Get tests to pass
* Fix pre-commit
* Eliminate extraneous dependencies from vendored Poetry

**Comment by maresb** [comment]
Rebased on #241 and cleaned up commits

**Comment by maresb** [comment]
Weird, the `.whl` is missing a bunch of files which are included in the sdist... I'll have to look into this once I get the chance.

**Comment by maresb** [comment]
I think the missing files may have simply been setuptools weirdness. Rebasing on Hatch, it looks like everything's there now.

**Comment by maresb** [comment]
BTW, my vendored poetry is also subvendoring all sorts of stuff. :roll_eyes: Do I need to write a license aggregator now? :joy:

**Comment by mariusvniekerk** [comment]
@maresb you can potentially make use of `vendoring` which is the thing that pip uses.  We can't use if for conda since conda can't easily be installed using pip, but for poetry it should work fine.  `vendoring` takes care of license aggregation etc.

**Comment by maresb** [comment]
Unfortunately your advice came slightly too late. I'm just putting the finishing touches on a tool I made yesterday.

**Comment by maresb** [comment]
This seems to be fundamentally working. But I still want to see if I can simplify things by using `vendoring`...

**Comment by maresb** [comment]
Ok, this is almost ready to go. `vendoring` allowed me to make a few steps declarative rather than imperative, but it made a big mess of the subvendored licenses. I think I just need to do some quick refactoring into a cleanup script.

**Comment by mariusvniekerk** [comment]
@maresb I've got a similar one in #256 that uses vendoring to update conda

**Review by mariusvniekerk — APPROVED** [review]

**Pull request merged**
